name: Terraform Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Terraform Init
        run: terraform init -backend=false
      - name: Terraform Validate
        run: terraform validate -no-color
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.3
      - name: TFLint
        run: |
          tflint --init
          tflint
